### YamlMime:UniversalReference
items:
  - uid: '@azure/servicefabric.TestErrorChaosEvent'
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - '@azure/servicefabric.TestErrorChaosEvent.kind'
      - '@azure/servicefabric.TestErrorChaosEvent.reason'
      - '@azure/servicefabric.TestErrorChaosEvent.timeStampUtc'
    langs:
      - typeScript
    type: interface
    summary: |-
      Chaos エンジンで予期しないイベントが発生したときに生成される混乱イベントについて説明します。
      たとえば、エンティティの障害発生中に一貫性があり、中、クラスター スナップショットにより Chaos が見つかりましたこと、エンティティが既にエラーが発生しました--予期しないイベントであります。
    package: '@azure/servicefabric'
  - uid: '@azure/servicefabric.TestErrorChaosEvent.kind'
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: ポリモーフィックな識別子
    syntax:
      content: 'kind: "TestError"'
      return:
        type:
          - '"TestError"'
    package: '@azure/servicefabric'
  - uid: '@azure/servicefabric.TestErrorChaosEvent.reason'
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: TestErrorChaosEvent が生成された理由について説明します。 たとえば、Chaos はしようとするパーティションの障害が、TestErrorEvent が生成される、パーティションは、フォールト トレラントではない理由を示すそのパーティションは、フォールト トレラントでは不要になったを検索します。
    optional: true
    syntax:
      content: 'reason?: undefined | string'
      return:
        type:
          - undefined | string
    package: '@azure/servicefabric'
  - uid: '@azure/servicefabric.TestErrorChaosEvent.timeStampUtc'
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: この混乱イベントが生成されたときの UTC のタイムスタンプ。
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: '@azure/servicefabric'